GET http://localhost:5000/api/grade

###
POST http://localhost:5000/api/grade
Content-Type: application/json

{
    "grade": 1,
    "wilder": "Alex Doe",
    "skill": "Typescript",
    "city": "Lille"

}